name: CI/CD

on: 
  push:
    branches: [master, main] # Déclenche le déploiement à chaque push sur la branche main ou master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

    #   - name: cloner le code
    #     uses: actions/checkout@v3

    #   - name: installer node js
    #     uses: actions/setup-node@v3
    #     with: 
    #       node-version: "22"
        
    #   - name: Installer les dépandances
    #     run: npm install

    #   - name: Lancer les tests
    #     run: npm test
      
    #   - name: Déploiement sur un vps avec ssh
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SSH_HOST }}
    #       username: ${{ secrets.SSH_USER }}
    #       key: ${{secrets.SSH_KEY}}
    #       port: ${{secrets.SSH_PORT}}
    #       script: |
    #         cd ~/workflows || mkdir ~/workflows && cd ~/workflows
    #         git clone https://github.com/${{github.repository}} . || git pull
    #         npm install
    #         pm2 delete my_api_node || true
    #         pm2 start index.js --name my_api_node
    #         pm2 save
    #         pm2 list




